# STAR HERE and create your fist db entry
http://localhost:8000
Content-Type: application/json; charset=utf-8
POST /api/$entityName;format="Camel,lower"$
{"name": "two", "value": 2223.12}

# Get the last update to named $entityName;format="Camel,lower"$
http://localhost:8000
Content-Type: application/json; charset=utf-8
GET /api/$entityName;format="Camel,lower"$/one

# Delete by name
http://localhost:8000
Content-Type: application/json; charset=utf-8
DELETE /api/$entityName;format="Camel,lower"$/one

